name: PipelineWorkFlow

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        name: Azure Pipeline
        runs-on: ubuntu-latest
        steps:
            - name: Azure Pipeline Action
              uses: Azure/pipelines@v1
              with:
                azure-devops-project-url: https://dev.azure.com/SauravAZ400/AgileProject
                azure-pipeline-name: 'saurav97sd.AzurePipelineApp'
                azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}